### ISSUE TITLE
Cross platform pre-commit hook setup

### ISSUE THREAD

**Issue by santosh** [wednesday-solutions/go-template#84]
I was trying to setup this template by following the getting started on the [README](https://github.com/wednesday-solutions/go-template/blob/master/README.MD#getting-started). 

I tried running `pre-commit-setup.sh` with bash but it exited with non-zero return code. `brew` wasn't found on my system.

Is this template expected to be used on MacOS only? If not can we have the `pre-commit` installation done by `pip`? I hope python comes by default on MacOS?

Requesting feedback.

**Comment by alichherawalla** [comment]
Hi @santosh, 

Thanks for reaching out. At this point in time, the template only has support for macOS. 

We're working on adding support for other operating systems as well and will be able to support it in the future.
